/**
 * Template Strings — all user-visible text for the templates feature.
 * Used by templateDefinitions.ts (template content) and UI components.
 */
export const templateStrings = {
    pickerTitle: 'Choose a Starting Point',
    blankCanvas: 'Blank Canvas',
    blankCanvasDesc: 'Start fresh — build your own structure from scratch',
    nodesBadge: '{count} nodes',
    nodesBadgeSingular: '1 node',
    customSection: 'My Templates',
    loadingCustom: 'Loading your templates\u2026',
    builtInSection: 'Built-in Templates',
    saveAs: 'Save as Template',
    saveAsDialogTitle: 'Save Workspace as Template',
    templateNameLabel: 'Template Name',
    saveBtn: 'Save Template',
    cancelBtn: 'Cancel',
    deleteBtn: 'Delete',
    deleteConfirmTitle: 'Delete Template',
    deleteConfirmMessage: 'This template will be permanently removed.',
    errors: {
        maxTemplatesReached: 'You can only save up to 10 custom templates. Delete one first.',
        emptyCanvas: 'Add at least one node before saving as a template.',
        nameRequired: 'Template name is required.',
        nameTooLong: 'Template name must be 50 characters or fewer.',
        saveFailed: 'Failed to save template. Please try again.',
        loadFailed: 'Failed to load your templates.',
        deleteFailed: 'Failed to delete template. Please try again.',
    },
    basb: {
        name: 'BASB CODE Framework',
        description: 'Build Your Second Brain: Capture → Organize → Distill → Express',
        captureHeading: 'Capture — Fleeting Notes',
        captureOutput: 'Drop any idea, thought, insight, or quote here as you encounter it. Raw is good — don\'t organize yet.',
        captureRefHeading: 'Capture — Reference Material',
        captureRefOutput: 'Useful articles, links, books, or documents you\'ve saved. What\'s worth keeping?',
        organizeProjectsHeading: 'Organize — By Project',
        organizeProjectsOutput: 'Which active projects do your captures serve? List project names and link relevant notes.',
        organizeAreasHeading: 'Organize — By Area',
        organizeAreasOutput: 'Which ongoing areas of responsibility do these notes belong to? (Health, Finance, Learning...)',
        distillInsightsHeading: 'Distill — Key Insights',
        distillInsightsOutput: 'What are the most valuable ideas from your captures? Bold the single best insight from each source.',
        distillQuestionsHeading: 'Distill — Open Questions',
        distillQuestionsOutput: 'What questions do your notes raise that you haven\'t answered yet?',
        expressNowHeading: 'Express — Creating Now',
        expressNowOutput: 'What are you working on right now that uses these insights? Link to your work-in-progress.',
        expressNextHeading: 'Express — Inspired Ideas',
        expressNextOutput: 'What could you create, write, share, or build using these distilled insights as raw material?',
    },
    project: {
        name: 'Project Kickoff',
        description: 'Capture goal, scope, timeline, risks, and resources for a new project',
        goalHeading: 'Goal',
        goalOutput: 'What does success look like? Write a clear, measurable outcome statement.',
        scopeInHeading: 'Scope In',
        scopeInOutput: 'What deliverables are explicitly included? Be specific about boundaries.',
        scopeOutHeading: 'Scope Out',
        scopeOutOutput: 'What are we NOT doing? List explicit non-goals to prevent scope creep.',
        timelineHeading: 'Timeline',
        timelineOutput: 'Key milestones: [Date] — Setup  /  [Date] — Build  /  [Date] — Launch',
        risksHeading: 'Risks',
        risksOutput: 'What could go wrong? Rate each: likelihood × impact. Add mitigation ideas.',
        resourcesHeading: 'Resources',
        resourcesOutput: 'Who and what do you need? People, tools, budget, and access.',
        stakeholdersHeading: 'Stakeholders',
        stakeholdersOutput: 'Who cares about this project? Who is Responsible / Consulted / Informed?',
        questionsHeading: 'Open Questions',
        questionsOutput: 'What decisions haven\'t been made yet? What information are you still waiting for?',
    },
    research: {
        name: 'Research Canvas',
        description: 'Structure a research question with sub-questions, evidence, and synthesis',
        questionHeading: 'Research Question',
        questionOutput: 'What are you trying to understand? Make it specific and answerable. A good question has a "how" or "why".',
        sub1Heading: 'Sub-question A',
        sub1Output: 'Break down the main question into a smaller, focused inquiry.',
        sub2Heading: 'Sub-question B',
        sub2Output: 'A different angle or dimension of the main question.',
        sub3Heading: 'Sub-question C',
        sub3Output: 'A counter-argument or alternative explanation to test.',
        evAHeading: 'Evidence A',
        evAOutput: 'Quote, data, or source that addresses Sub-question A. Include citation.',
        evBHeading: 'Evidence B',
        evBOutput: 'Quote, data, or source that addresses Sub-question B. Include citation.',
        evCHeading: 'Evidence C',
        evCOutput: 'Quote, data, or source that addresses Sub-question C. Include citation.',
        synthesisHeading: 'Synthesis',
        synthesisOutput: 'What do the sub-questions and evidence add up to? What\'s your answer to the main question?',
    },
    brainstorm: {
        name: 'Brainstorm Board',
        description: 'Divergent thinking — 8 idea slots, no connections, no judgment',
        ideaHeading: 'Idea {n}',
        ideaOutput: 'Type any idea here. Volume over quality — suspend judgment until review.',
    },
    review: {
        name: 'Weekly Review',
        description: 'Reflect on the week: what happened, what you learned, and what\'s next',
        happenedHeading: 'What Happened?',
        happenedOutput: 'Key events, meetings, completions, and setbacks from this week.',
        winsHeading: 'Wins',
        winsOutput: 'What went well? Even small wins count. What are you proud of?',
        strugglesHeading: 'Struggles',
        strugglesOutput: 'What didn\'t go as planned? What drained your energy or felt hard?',
        learnedHeading: 'What I Learned',
        learnedOutput: 'Insights, surprises, or shifts in understanding from this week.',
        openLoopsHeading: 'Open Loops',
        openLoopsOutput: 'Things started but not finished. Decisions left unmade. Promises to follow up on.',
        nextHeading: "What's Next?",
        nextOutput: 'Most important priorities and intentions for next week.',
        actionsHeading: 'Key Actions',
        actionsOutput: 'Specific tasks to carry forward. Add due dates where possible.',
        energyHeading: 'Energy & Gratitude',
        energyOutput: 'What\'s your energy level this week? What are you grateful for?',
    },
};
