export const canvasStrings = {
    nodeActionsLabel: 'Node actions',
    generating: 'Generating...',
    clearCanvas: 'Clear all nodes',
    clearConfirm: 'Are you sure you want to clear all nodes?',
    clearConfirmTitle: 'Clear Canvas',
    clearConfirmButton: 'Clear all',
    imageUploading: 'Uploading image...',
    imageUploadFailed: 'Image upload failed. Please try again.',
    imageReadFailed: 'Failed to read image file.',
    imageUnsafeUrl: 'Image URL failed security validation.',
    imageFileTooLarge: 'Image exceeds 5 MB size limit.',
    imageUnsupportedType: 'Unsupported image format. Use JPEG, PNG, GIF, or WebP.',
    zoomControls: {
        zoomIn: 'Zoom In',
        zoomOut: 'Zoom Out',

        lockCanvas: 'Lock Canvas',
        unlockCanvas: 'Unlock Canvas',
        radarLabel: 'Canvas radar — click to fit all nodes',
    },
    resize: {
        resizeNode: 'Resize node',
        resizeHandle: 'Drag to resize',
        corner: 'Corner resize handle',
        edge: 'Edge resize handle',
        expandWidth: 'Expand width',
        expandHeight: 'Expand height',
        reduceWidth: 'Reduce width',
        reduceHeight: 'Reduce height',
    },
};
