export const canvasStrings = {
    nodeActionsLabel: 'Node actions',
    generating: 'Generating...',
    clearCanvas: 'Clear all nodes',
    clearConfirm: 'Are you sure you want to clear all nodes?',
    clearConfirmTitle: 'Clear Canvas',
    clearConfirmButton: 'Clear all',
    imageUploading: 'Uploading image...',
    imageUploadFailed: 'Image upload failed. Please try again.',
    imageReadFailed: 'Failed to read image file.',
    imageUnsafeUrl: 'Image URL failed security validation.',
    imageFileTooLarge: 'Image exceeds 5 MB size limit.',
    imageUnsupportedType: 'Unsupported image format. Use JPEG, PNG, GIF, or WebP.',
    docUploading: 'Uploading document...',
    docUploadFailed: 'Document upload failed. Please try again.',
    docReadFailed: 'Failed to read document file.',
    docFileTooLarge: 'Document exceeds 15 MB size limit.',
    docUnsupportedType: 'Unsupported format. Use PDF, TXT, or CSV.',
    docMagicByteMismatch: 'File contents do not match declared type.',
    docParsingFailed: 'Failed to extract text from document.',
    docAiReady: 'AI Ready',
    docAiReadyTooltip: 'Document text extracted — available for AI generation',
    docProcessing: 'Processing document...',
    docDownload: 'Download',
    docOpenNewTab: 'Open in new tab',
    docRemove: 'Remove attachment',
    imageRemove: 'Remove image',
    docFormatNotSupported: 'This format is not yet supported. Use PDF, TXT, or CSV.',
    docAuthUnavailable: 'Authentication or workspace context unavailable.',
    docReadHeaderFailed: 'Failed to read file header.',
    doubleClickToCreate: {
        tooltip: 'Double-click to add a note',
    },
    zoomControls: {
        zoomIn: 'Zoom In',
        zoomOut: 'Zoom Out',

        lockCanvas: 'Lock Canvas',
        unlockCanvas: 'Unlock Canvas',
        radarLabel: 'Canvas radar — click to fit all nodes',
    },
    resize: {
        resizeNode: 'Resize node',
        resizeHandle: 'Drag to resize',
        corner: 'Corner resize handle',
        edge: 'Edge resize handle',
        expandWidth: 'Expand width',
        expandHeight: 'Expand height',
        reduceWidth: 'Reduce width',
        reduceHeight: 'Reduce height',
    },
    history: {
        undoDelete: 'Undo delete',
        undoBatchDelete: (count: number) => `Undo delete (${count} nodes)`,
        undoAdd: 'Undo add',
        undoMove: 'Undo move',
        undoEdge: 'Undo edge change',
        undoColor: 'Undo color change',
        undoTransform: 'Undo transform',
        redoAction: 'Redo',
        nothingToUndo: 'Nothing to undo',
        nothingToRedo: 'Nothing to redo',
        undoButton: 'Undo',
        undoTooltip: 'Undo last action (Ctrl+Z)',
        redoButton: 'Redo',
        redoTooltip: 'Redo last action (Ctrl+Shift+Z)',
        nodeDeleted: 'Node deleted',
        nodesDeleted: (count: number) => `${count} nodes deleted`,
        edgeDeleted: 'Connection removed',
        canvasCleared: 'Canvas cleared',
        arrangeUndone: 'Arrangement undone',
        arrangeUndoAction: 'Undo arrange',
        deleteNodesConfirmTitle: 'Delete nodes',
        deleteNodesConfirm: (count: number) => `Delete ${count} nodes? This can be undone.`,
        deleteNodesConfirmButton: 'Delete',
    },
    mindmap: {
        ariaLabel: 'Mindmap visualization',
        emptyFallback: 'Empty',
        emptyHint: 'Type a heading and press Enter to generate content, then view as mindmap',
        errorFallback: 'Unable to render mindmap',
        errorRetry: 'Retry',
        errorSwitchToText: 'Switch to Text View',
        convertEmpty: 'Add content first, then convert to mindmap',
        switchedToMindmap: 'Switched to Mindmap View',
        switchedToText: 'Switched to Text View',
        loading: 'Loading mindmap...',
    },
};
