export const settingsStrings = {
    title: 'Settings',
    appearance: 'Appearance',
    canvas: 'Canvas',
    account: 'Account',
    keyboard: 'Keyboard Shortcuts',
    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    themeSepia: 'Sepia',
    themeGrey: 'Grey',
    themeDarkBlack: 'Dark Black',
    canvasGrid: 'Show grid',
    autoSave: 'Auto-save',
    autoSaveInterval: 'Auto-save interval',
    seconds: 'seconds',
    compactMode: 'Compact mode',
    canvasScrollMode: 'Scroll behavior',
    canvasScrollZoom: 'Canvas Zoom',
    canvasScrollNavigate: 'Canvas Navigation',
    connectorStyle: 'Connector style',
    connectorSolid: 'Solid',
    connectorSubtle: 'Subtle',
    connectorThick: 'Thick',
    connectorDashed: 'Dashed',
    connectorDotted: 'Dotted',
    freeFlow: 'Free flow mode',
    gridColumnsLabel: 'Grid columns',
    gridColumnsAuto: 'Auto',
    gridColumnsAutoDescription: 'Adapt to window width',
    gridColumnsFixedDescription: (n: number) => `${n} column${n === 1 ? '' : 's'}`,
    canvasDisplay: 'Display',
    compactModeDescription: 'Reduce spacing for more content on screen',
    close: 'Close',
    about: 'About',
    version: 'Version',
    reportBug: 'Report a bug',
    changelog: 'Changelog',
    exportData: 'Export Data',
    exportDataDescription: 'Download all your notes and connections as JSON',
    dangerZone: 'Danger Zone',
    deleteAccount: 'Delete Account',
    deleteAccountTitle: 'Delete Account?',
    deleteAccountConfirm: 'This will permanently delete your account and all data. This action cannot be undone.',
    deleteAccountButton: 'Delete Permanently',
    reAuthRequired: 'Please sign in again to complete this action.',
    deleteAccountSuccess: 'Account deleted successfully.',
    deleteAccountFailed: 'Failed to delete account. Please try again.',
    exportSuccess: 'Workspace data exported successfully.',
    changelogUrl: 'https://github.com/user/actionstation/blob/main/CHANGELOG.md',
    reportBugUrl: 'https://github.com/user/actionstation/issues/new',
    autoAnalyzeDocuments: 'Auto-analyze documents',
    autoAnalyzeDocumentsHint: 'Automatically generates an AI insight node when you attach a document',
    toolbar: 'Toolbar',
    toolbarTitle: 'Icon Placement',
    toolbarDescription: 'Drag icons between zones to customize what appears in the UtilsBar and Context Menu. Icons not placed in either zone will be hidden.',
    toolbarUtilsBarZone: 'UtilsBar',
    toolbarUtilsBarHint: 'Hover bar on nodes',
    toolbarContextMenuZone: 'Context Menu',
    toolbarContextMenuHint: 'Right-click / "More…" menu',
    toolbarUnplacedZone: 'Available Icons',
    toolbarUnplacedHint: 'Drag to a zone above to enable',
    toolbarReset: 'Reset to Default',
    toolbarResetConfirm: 'Restore the default icon placement?',
    toolbarDragHint: 'Drag to reorder or move between zones',
    toolbarEmpty: 'Drag icons here',
    toolbarNoUnplaced: 'All icons are placed',
    toolbarMoveUp: 'Move up',
    toolbarMoveDown: 'Move down',
    toolbarRemove: 'Remove from zone',
    toolbarCapacity: 'of',
    toolbarZoneFull: 'Zone is full — remove an icon first',
    toolbarMoreButton: '"More…" button opens Context Menu (always visible)',
};
