import { authStrings } from './authStrings';
import { workspaceStrings } from './workspaceStrings';
import { canvasStrings } from './canvasStrings';
import { knowledgeBankStrings } from './knowledgeBankStrings';
import { calendarStrings } from './calendarStrings';
import { nodePoolStrings } from './nodePoolStrings';
import { securityStrings } from './securityStrings';
import { settingsStrings } from './settingsStrings';
import { documentAgentStrings } from '@/features/documentAgent/strings/documentAgentStrings';
import { synthesisStrings } from '@/features/synthesis/strings/synthesisStrings';
import { exportStrings } from '@/features/export/strings/exportStrings';
import { contextMenuStrings } from './contextMenuStrings';

export const strings = {
    app: {
        name: 'ActionStation',
        tagline: 'Think visually. Connect ideas.',
        description: 'AI-powered infinite whiteboard for creating, connecting, and synthesizing ideas.',
        keywords: 'AI whiteboard, visual thinking, idea canvas, brainstorming, mind mapping, productivity',
    },
    auth: authStrings,
    workspace: workspaceStrings,
    canvas: canvasStrings,
    ideaCard: {
        headingPlaceholder: 'Title',
        headingAiPlaceholder: 'Ask AI',
        aiPillLabel: '✨ AI',
        dividerLabel: 'Separator',
        promptLabel: 'Prompt',
        outputLabel: 'Output',
        regenerate: 'Regenerate',
        branch: 'Branch',
        delete: 'Delete',
        expand: 'Expand',
        collapse: 'Collapse',
        expandPrompt: 'Expand prompt',
        collapsePrompt: 'Collapse prompt',
        noOutput: 'Type text to save, or / for commands',
        inputPlaceholder: 'Type a note...',
        aiDividerLabel: 'AI Response',
        transform: 'Transform',
        transforming: 'Transforming...',
    },
    transformations: {
        refine: 'Refine',
        shorten: 'Shorten',
        lengthen: 'Lengthen',
        proofread: 'Proofread',
        refineDescription: 'Improve clarity and polish',
        shortenDescription: 'Make more concise',
        lengthenDescription: 'Expand with more detail',
        proofreadDescription: 'Fix grammar and spelling',
    },
    errors: {
        generic: 'Something went wrong. Please try again.',
        networkError: 'Network error. Please check your connection.',
        aiError: 'AI generation failed. Please try again.',
        quotaExceeded: 'API quota exceeded. Please try again later.',
    },
    common: {
        confirm: 'Confirm',
        submit: 'Submit',
        cancel: 'Cancel',
        save: 'Save',
        retry: 'Retry',
        loading: 'Loading...',
        loadingComponent: 'Loading component...',
        comingSoon: 'Coming soon!',
        closeSymbol: '\u00D7',
    },
    settings: settingsStrings,
    shortcuts: {
        openSettings: 'Open Settings',
        addNode: 'Add Node',
        quickCapture: 'Quick Capture',
        deleteNode: 'Delete Node',
        clearSelection: 'Clear Selection',
        undo: 'Undo',
        redo: 'Redo',
        search: 'Search',
    },
    search: {
        placeholder: 'Search notes...',
        noResults: 'No results found',
        resultsCount: 'results',
        inWorkspace: 'in',
        prompt: 'Prompt',
        heading: 'Heading',
        output: 'Output',
    },
    tags: {
        addTag: 'Add tag',
        placeholder: 'Add tag...',
        removeTag: 'Remove tag',
        noTags: 'No tags',
    },
    nodeUtils: {
        aiActions: 'AI Actions',
        collapse: 'Collapse',
        more: 'More actions',
        moreIcon: '•••',
        collapseShortcut: 'C',
        color: 'Color',
        connect: 'Connect',
        copy: 'Copy',
        copyError: 'Failed to copy',
        copyShortcut: '⌘C',
        copySuccess: 'Copied to clipboard',
        delete: 'Delete',
        deleteShortcut: '⌫',
        duplicate: 'Duplicate',
        duplicateError: 'Failed to duplicate node',
        duplicateSuccess: 'Node duplicated',
        exitFocus: 'Exit focus',
        expand: 'Expand',
        focus: 'Focus',
        focusShortcut: 'F',
        image: 'Image',
        attachment: 'Attachment',
        attachmentTooltip: 'Attach a PDF, TXT, or CSV file',
        noOtherWorkspaces: 'No other workspaces available',
        pin: 'Pin',
        regenerate: 'Regenerate',
        share: 'Share',
        shareError: 'Failed to share node',
        shareSuccess: 'Node shared successfully',
        shareToWorkspace: 'Share to workspace',
        nodeColorDefault: 'Default',
        nodeColorRed: 'Red (Attention)',
        nodeColorYellow: 'Yellow (In Progress)',
        nodeColorGreen: 'Green (Complete)',
        tags: 'Tags',
        tagsShortcut: 'T',
        unpin: 'Unpin',
    },
    tooltip: {
        shortcutSeparator: ' ',
    },
    edge: {
        deleteConnection: 'Delete connection',
    },
    resize: canvasStrings.resize,
    performance: {
        cls: 'Cumulative Layout Shift',
        fcp: 'First Contentful Paint',
        fid: 'First Input Delay',
        inp: 'Interaction to Next Paint',
        lcp: 'Largest Contentful Paint',
        ttfb: 'Time to First Byte',
    },
    offline: {
        online: 'Online',
        offline: 'Offline',
        saving: 'Saving...',
        saved: 'All changes saved',
        saveError: 'Save failed',
        saveFailed: 'Failed to save changes. Will retry when online.',
        queued: 'Changes queued',
        queuedCount: 'pending changes',
        syncComplete: 'All changes synced',
        syncFailed: 'Sync failed. Will retry.',
        offlineBanner: 'You are offline. Changes will be saved locally.',
        reconnected: 'Back online. Syncing changes...',
        retrying: 'Retrying save...',
        queueFull: 'Offline queue full. Oldest changes may be lost.',
        dismiss: 'Dismiss',
        pendingSync: 'pending sync',
        loadingFromCache: 'Loading from local cache...',
        noOfflineData: 'No offline data available for this workspace.',
    },
    slashCommands: {
        aiGenerate: {
            label: 'AI Generate',
            description: 'Generate content with AI',
        },
        insertImage: {
            label: 'Insert Image',
            description: 'Upload an image from your device',
        },
        insertDocument: {
            label: 'Attach Document',
            description: 'Attach a PDF, TXT, or CSV file',
        },
        analyzeDocument: {
            label: 'Analyze Document',
            description: 'Extract insights from attached documents',
        },
        noResults: 'No commands found',
        menuLabel: 'Slash commands',
        prefixSeparator: ':',
        prefixLabel: 'Command mode active',
    },
    editing: {
        enterEditMode: 'Enter edit mode',
        exitEditMode: 'Exit edit mode',
        unsavedDraft: 'Unsaved draft',
        draftSaved: 'Draft saved',
    },
    linkPreview: {
        loading: 'Loading preview...',
        unavailable: 'Preview unavailable',
        openLink: 'Open link',
        removePreview: 'Remove preview',
        refreshPreview: 'Refresh preview',
        fetchError: 'Could not load link preview',
        proxyError: 'Link preview proxy unavailable',
        authRequired: 'Sign in to see link previews',
    },
    layout: {
        arrangeNodes: 'Auto Arrange',
        arrangeTooltip: 'Arrange nodes in masonry grid',
        arrangeSuccess: 'Nodes arranged in grid',
        arrangeSuccessWithPinned: (pinnedCount: number) =>
            `Nodes arranged in grid (${pinnedCount} pinned ${pinnedCount === 1 ? 'node' : 'nodes'} kept in place)`,
        allNodesPinned: 'All nodes are pinned — nothing to arrange',
        arrangingNodes: 'Arranging nodes...',
        neighborAwareLayout: 'Neighbor-aware layout',
        incrementalRearrange: 'Incremental rearrange',
        columnCount: 'columns',
        gridGap: 'Grid gap',
        gridPadding: 'Grid padding',
    },
    pwa: {
        updateAvailable: 'A new version is available.',
        updateNow: 'Update now',
        dismissUpdate: 'Later',
        appName: 'ActionStation',
        appShortName: 'ActionStation',
        appDescription: 'AI-powered infinite whiteboard for visual thinking.',
    },
    pinning: {
        pin: 'Pin for offline',
        unpin: 'Unpin',
        pinTooltip: 'Save this workspace for offline access',
        unpinTooltip: 'Remove offline access for this workspace',
        pinned: 'Available offline',
        unpinned: 'Online only',
        pinSuccess: 'Workspace pinned for offline use',
        unpinSuccess: 'Workspace unpinned',
        storageUsage: 'Storage used',
    },
    subscription: {
        free: 'Free',
        pro: 'Pro',
        upgradeTitle: 'Upgrade to Pro',
        upgradeMessage: 'This feature requires a Pro subscription:',
        upgradeCta: 'Upgrade now',
        dismissUpgrade: 'Maybe later',
        currentPlan: 'Current plan',
        expiresAt: 'Expires',
        featureLocked: 'This feature requires a Pro subscription',
    },
    backgroundSync: {
        syncing: 'Syncing in background...',
        syncComplete: 'Background sync complete',
        syncFailed: 'Background sync failed. Will retry.',
        notSupported: 'Background sync not available in this browser.',
    },
    offlineFallback: {
        title: 'You are offline',
        message: 'Connect to the internet to access your workspaces. Cached workspaces will load automatically.',
        retryButton: 'Try again',
        noDataTitle: 'No cached data',
        noDataMessage: 'Visit your workspaces while online to cache them for offline use.',
    },
    sidebar: {
        ariaLabel: 'Workspace sidebar',
        pin: 'Pin sidebar',
        unpin: 'Unpin sidebar',
        pinTooltip: 'Keep sidebar always visible',
        unpinTooltip: 'Collapse sidebar; hover to reveal',
    },
    formatting: {
        bold: 'Bold',
        italic: 'Italic',
        strikethrough: 'Strikethrough',
        code: 'Code',
        link: 'Link',
        boldDisplay: 'B',
        italicDisplay: 'I',
        strikethroughDisplay: 'S',
        codeDisplay: '</>',
        linkDisplay: '\uD83D\uDD17',
        linkPrompt: 'Enter URL:',
    },
    knowledgeBank: knowledgeBankStrings,
    nodePool: nodePoolStrings,
    calendar: calendarStrings,
    security: securityStrings,
    documentAgent: documentAgentStrings,
    synthesis: synthesisStrings,
    export: exportStrings,
    contextMenu: contextMenuStrings,
} as const;

export type StringKeys = typeof strings;
