export const snapshotStrings = {
    shareCanvas: 'Share Canvas',
    createLink: 'Create shareable link',
    creating: 'Creating link\u2026',
    linkReady: 'Link ready! Expires in 30 days.',
    copyLink: 'Copy link',
    copied: 'Link copied!',
    expiredTitle: 'This canvas has expired',
    expiredMessage: 'The owner can create a new share link.',
    notFoundTitle: 'Canvas not found',
    notFoundMessage: 'This link may be invalid or the canvas was never shared.',
    loadingCanvas: 'Loading canvas\u2026',
    readOnly: 'Read-only view',
    nodesCount: '{count} nodes',
    nodesCountSingular: '1 node',
    errorCreating: 'Failed to create share link',
    errorLoading: 'Failed to load canvas',
    untitledWorkspace: 'Untitled',
} as const;
